### PR TITLE
Add user authentiation.

### PR DESCRIPTION
**Pull request by lincoln1883**
For this milestone i created authentication :
- [ ] Create user sign up feature
  - successfully sending the user object to the server to create a user.
- [ ] Create user login feature.
  - successfully sending the user object to the server to login the user and send user credentials back to the frontend.
- [ ] create user logout feature.
  - successfully using the user credentials to loug the user out of the backend and also logging the user out of the frontend
  - [ ] upon a successful logging the user is navigated to the trades list page.
  - [ ] upon a successful loggout the app is refreshed and returned to the splash screen.
  - [ ] if the logged out user tries to continue using the app he is redirected to the splash page. 

please create a .env file in root of your app and add this code before starting the application (REACT_APP_API_URL=http://localhost:3001/api/v1
REACT_APP_API_AUTH_URL=http://localhost:3001/)

### CODE REVIEW

**Comment by MoyasiGinko** [comment]
Hello @lincoln1883 👋, This is an `Update` regarding a minor change made into your branch.
After merging the `footer-toolbar` to development there was a conflict with your branch in the `navbar.jsx` . So, i fixed it along with the linters on behalf of you. Please check the commits for better understanding the changes.

**Comment by lincoln1883** [comment]
Why do I see so many dependencies removed?

**Review by ibugithub — APPROVED** [review]
# STATUS: APPROVED 🟢 ✔️ 

## Hi @lincoln1883  👋 

You did a great job and Thanks so much for all of your hard work  🎉

 

## Highlights 🎯 
✔️ The Signup Engine is working fine
✔️ The Login Engine is working fine
✔️ Token storing in Local storage system is also working fine
✔️ No linter errors

Cheers, and Happy coding!👏👏👏

But I Have created a list of options Please take a look at them. 
 
1=> Check out the video I've shown a little bug in it.

https://github.com/lincoln1883/appointment-capstone-frontend/assets/61221884/60697991-6737-4994-9f10-47cac7c50812


2=> The form border color is always red.
but it should be dynamic.
image


3=> When successfully a user signs up it's not showing any msg or redirect to anywhere. 
It should show the error msg also. 

4 => We should have both login navigation on the signup page and sign-up navigation on the login page.

5=> The password field should have a password validation. exam

6 => The password field should have a password validation. example => password must have at least a char and a num

**Comment by lincoln1883** [comment]
You have valid points I'm still working on the login redirect.

**Pull request merged**
